name: Generate Course Website

on:
  push:
    branches:
      - master   # or "main" if your repo default branch is main
  workflow_dispatch:  # allows manual run from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run generator script
      run: |
        python generate_site.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html style.css
        git commit -m "Auto-generate site via GitHub Actions" || echo "No changes to commit"
        git push
